# General settings
title: Marcin Abram
title_html: "Marcin Abram"
description:
  en: theoretical physicist and machine learning engineer
baseurl: ""
url: "https://marcinabram.github.io"

langs: ["en"]
defaults:
  - scope:
      path: ""
    values:
      lang: "en"

# Author
author: Marcin Abram

email: 
github_username: marcinabram
linkedin_username: marabram
author_website: https://marcinabram.github.io

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

# Build settings
theme: academic
plugins:
  - jekyll-feed
exclude:
  - jekyll_build.sh
  - Gemfile
  - Gemfile.lock
